In [1]:
import pandas as pd
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("08-Linear-Regression-Models/Advertising.csv")

In [3]:
df.head()

,TV,radio,newspaper,sales
0,230.1,37.8,69.2,22.1
1,44.5,39.3,45.1,10.4
2,17.2,45.9,69.3,9.3
3,151.5,41.3,58.5,18.5
4,180.8,10.8,58.4,12.9


In [4]:
X = df.drop('sales', axis=1)

In [5]:
y = df['sales']

In [6]:
from sklearn.preprocessing import PolynomialFeatures

In [8]:
poly_features = polynomial_converter.fit_transform(X)

In [9]:
poly_features.shape

(200, 19)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(poly_features, y, test_size=0.30, random_state=101)

In [12]:
X_train.shape

(140, 19)

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()

In [15]:
scaler.fit(X_train)

,copy,True
,with_mean,True
,with_std,True


In [16]:
X_train = scaler.transform(X_train)

In [17]:
X_test = scaler.transform(X_test)

In [18]:
X_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

In [19]:
poly_features[0]

array([2.30100000e+02, 3.78000000e+01, 6.92000000e+01, 5.29460100e+04,
       8.69778000e+03, 1.59229200e+04, 1.42884000e+03, 2.61576000e+03,
       4.78864000e+03, 1.21828769e+07, 2.00135918e+06, 3.66386389e+06,
       3.28776084e+05, 6.01886376e+05, 1.10186606e+06, 5.40101520e+04,
       9.88757280e+04, 1.81010592e+05, 3.31373888e+05])

In [20]:
from sklearn.linear_model import Ridge

In [21]:
ridge_model = Ridge(alpha=10)

In [22]:
ridge_model.fit(X_train, y_train)

,alpha,10
,fit_intercept,True
,copy_X,True
,max_iter,None
,tol,0.0001
,solver,'auto'
,positive,False
,random_state,None


In [23]:
test_predictions = ridge_model.predict(X_test)

In [24]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [25]:
MAE = mean_absolute_error(y_test, test_predictions)

In [26]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [27]:
MAE

0.5774404204714166

In [28]:
RMSE

np.float64(0.8946386461319648)

In [29]:
from sklearn.linear_model import RidgeCV

In [30]:
alphas = np.arange(0.03, 0.036, 0.002)

In [31]:
ridge_cv_model = RidgeCV(alphas=alphas, scoring='neg_mean_absolute_error')

In [32]:
ridge_cv_model.fit(X_train, y_train)

,alphas,"array([0.03 , 0.032, 0.034])"
,fit_intercept,True
,scoring,'neg_mean_absolute_error'
,cv,None
,gcv_mode,None
,store_cv_results,False
,alpha_per_target,False


In [33]:
ridge_cv_model.alpha_

np.float64(0.034)

In [34]:
from sklearn.metrics import get_scorer_names

In [35]:
test_predictions = ridge_cv_model.predict(X_test)

In [36]:
MAE = mean_squared_error(y_test, test_predictions)

In [37]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [38]:
MAE

0.350096085544906

In [39]:
RMSE

np.float64(0.5916891798443723)

In [40]:
ridge_cv_model.coef_

array([ 6.35423607,  0.53275916,  0.34628204, -8.42699296,  4.93412287,
       -1.51532945, -1.28550853,  0.6987823 ,  0.16719928,  3.85461056,
       -1.50567833,  1.23998099,  0.53138815, -0.29765577,  0.09203623,
        0.64047236, -0.27459808, -0.15328233, -0.17456777])

In [41]:
ridge_cv_model.best_score_

-0.3608256631824797

In [42]:
from sklearn.linear_model import LassoCV

In [43]:
lasso_cv_model = LassoCV(eps=0.001, alphas=100, max_iter=100000)

In [44]:
lasso_cv_model.fit(X_train, y_train)

,eps,0.001
,n_alphas,'deprecated'
,alphas,100
,fit_intercept,True
,precompute,'auto'
,max_iter,100000
,tol,0.0001
,copy_X,True
,cv,None
,verbose,False
,n_jobs,None


In [45]:
lasso_cv_model.alpha_

np.float64(0.004943070909225831)

In [46]:
test_predictions = lasso_cv_model.predict(X_test)

In [47]:
MAE = mean_squared_error(y_test, test_predictions)

In [48]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [49]:
MAE

0.367616757419907

In [50]:
RMSE

np.float64(0.6063140748984036)

In [51]:
lasso_cv_model.coef_

array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

In [52]:
from sklearn.linear_model import ElasticNetCV

In [57]:
elastic_model = ElasticNetCV(l1_ratio=[.1, .5, .7, .9, .99, 1], eps=0.001, n_alphas=100, max_iter=1000000)

In [58]:
elastic_model.fit(X_train, y_train)

C:\Users\Asus\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:1622: FutureWarning: 'n_alphas' was deprecated in 1.7 and will be removed in 1.9. 'alphas' now accepts an integer value which removes the need to pass 'n_alphas'. The default value of 'alphas' will change from None to 100 in 1.9. Pass an explicit value to 'alphas' and leave 'n_alphas' to its default value to silence this warning.
  warnings.warn(


,l1_ratio,"[0.1, 0.5, ...]"
,eps,0.001
,n_alphas,100
,alphas,'warn'
,fit_intercept,True
,precompute,'auto'
,max_iter,1000000
,tol,0.0001
,cv,None
,copy_X,True
,verbose,0


In [59]:
elastic_model.l1_ratio_

np.float64(1.0)

In [60]:
elastic_model.alpha_

np.float64(0.004943070909225831)

In [61]:
test_predictions = elastic_model.predict(X_test)

In [62]:
MSE = mean_squared_error(y_test, test_predictions)

In [63]:
RMSE = np.sqrt(mean_squared_error(y_test, test_predictions))

In [64]:
MSE

0.367616757419907

In [65]:
RMSE

np.float64(0.6063140748984036)